### Post API SIGNUP
POST http://localhost:4000/librarian/addtodb HTTP/1.1
Content-Type: application/json

{
    "fullName": "Shahzaib Saleem",
    "email":"emad123@outlook.com",
    "password":"123123"
}


###LOGIN
POST http://localhost:4000/librarian/login HTTP/1.1
Content-Type: application/json

{
    "email":"emad123@outlook.com",
    "password":"123123"
}